# fly.toml app configuration file generated for llmux on 2026-01-19T15:02:10+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'llmux'
primary_region = 'iad'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[[vm]]
  memory = '512mb'
  cpus = 1

[[services]]
  internal_port = 8081
  protocol = 'tcp'
  auto_stop_machines = 'suspend'
  auto_start_machiens = 'true'
  min_machines_running = 0
    [[services.ports]]
      handlers = ["http"]
      port = 80

[env]
  TS_HOSTNAME = "llmux-backend"
